Biostrings2classes rmd
Bioconductor/Biostrings pull request #83
Opened 2022-09-21 14:26 UTC by villafup

@Bioconductor/sweave2rmd for review

2023-02-17 22:52 UTC, jwokaty commented
@villafup Please remove .Rnw file. I don't think you need to modify the DESCRIPTION because there are other PRs that add BiocStyle

2023-06-27 18:03 UTC, hpages commented
@villafup @jwokaty Where are we standing with this PR?

2023-06-27 18:36 UTC, jwokaty commented
We are waiting on some changes from @villafup. I'll slack him :)

2023-07-17 21:17 UTC, jwokaty commented on vignettes/Biostrings2Classes.Rmd
> +string (these views being typicallythe matches returned by a search
space between `typicallythe`

2023-07-17 21:28 UTC, jwokaty commented on vignettes/Biostrings2Classes.Rmd
> +replacing the `r Biocpkg('Biostrings')` class (implemented in `r Biocpkg('Biostrings')` 1) by 2 new
I think lines 37 and 40 (the first reference only) reference an old `BioString` class, so replace

    `r Biocpkg('Biostrings')`
    
with

    BioString

2023-07-17 22:10 UTC, jwokaty requested changes
@villafup Just 3 small changes.

I noticed that it doesn't currently generate the Rmd via `R CMD build` because `VignetteBuild: knitr` isn't in this version of the DESCRIPTION file; however, when it's merged, it should create the .Rmd.

It'll be ready for Herve after these changes.

2024-06-06 19:56 UTC, ahl27 commented
@hpages @jwokaty what is the status of this and #90 ? Are these still being worked on, and if not, can we merge/close them?

2024-06-06 22:32 UTC, hpages commented
I'm surprised this vignette made it to the sweave2rmd list. It's very old and outdated and doesn't have much value anymore. It was written to document the classes that I introduced when I took over the package and transitioned it from **Biostrings** 1 to **Biostrings** 2 about 18 years ago! The only reason it's still around is that **Biostrings** doesn't have a good general vignette, so I guess having the "Biostrings 2 classes" vignette was better than nothing. However we should start thinking about addressing that @ahl27. In the mean time I think it's ok to close this unless @jwokaty or @villafup oppose. Thanks!

2024-06-07 00:00 UTC, ahl27 commented
Sounds good, I'll wait for either of them to chime in to confirm and then we can consider closing it. 

Is the other PR still something we need to merge? I can ping you on that PR so the conversation stays localized to the PR

2024-10-21 23:43 UTC, closed without merging