Converting MultipleAlinments.Rnw to Rmarkdown
Bioconductor/Biostrings pull request #90
Opened 2022-12-12 17:20 UTC by BerylKanali

@jwokaty 
Take a look at the changes
Issues I have:

1. - In the description file when writing authors using this format 
```
Authors@R: c(
  person("Hervé", "Pagès", role=c("aut", "cre"),
```
is it okay for the first name to be the intials as in the previous format.
2. Graph position not as exact as PDF
3. Size of graph(someone should not scroll to thee the whole graph)
6. The `dev.off `gives a different output when I knit

```
null device 
          1 
```
is the correct output but after in the HTML it shows 
```
## png 
##   2
```

2022-12-14 04:00 UTC, jwokaty commented
Let's follow the previous format using initials for the `DESCRIPTION`.

Looking at https://github.com/Bioconductor/Biostrings/blob/c94e8fb082601cf3e3998df82cf1a9b39c72cb27/vignettes/MultipleAlignments.Rnw#L278-L283, I suspect that the original authors moved the figure to waste less space on the pages of the PDF. Let's allow the figures to follow their code naturally since the HTML document will not have the same problem.

Since the PDF isn't displaying as nicely as we'd like, I'd like to ask @hpages if we can `png` format instead? Or if there's a way to make the PDF display nicely, that suggestion would be helpful.

Lastly, I think we don't have to worry about the value of `dev.off()` as this is turning off the device and returning the value of that device I believe (we can check with `?dev.off`). `dev.off` is always the "stub", which is `null device 1` on build system, which will generate the vignettes available on bioconductor.org. For users running this code, it will almost always show something else.

2023-01-03 14:57 UTC, BerylKanali commented
@jwokaty 
This is ready for review apart from the graph issue talked about above. I did `R CMD build` and `R CMD check` and found no errors.

2023-01-06 02:24 UTC, jwokaty requested changes
Thanks for working on this. I've marked a few items to correct; a few them, such as using back ticks (`) rather than asterisks (*) are repetitive but I marked them so that they can be checked again.

Before you ask for a review, make sure to review your knitted document against the current PDF that you find on the landing pages for each package. 

@hpages Can we use .pngs for the figures rather than .pdfs since they don't format well? (If there's a better way to format them, please let us know.)

2023-01-06 02:24 UTC, jwokaty commented on DESCRIPTION
> +	  comment="Converted 'MultipleAlignments' vignette from Sweave to RMarkdown."))
Fix the identation of line 15 and 20. See https://github.com/Bioconductor/GenomicAlignments/blob/master/DESCRIPTION as a reference.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +- name: "Fred Hutchinson Cancer Research Center, Seattle, WA"
Line 5-6 should be the `affiliation` for Marc.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +
Remove extra lines, such as 9-11, 13

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +date: "Edited: November 1, 2022; compiled: `r format(Sys.time(), '%d %B, %Y')`"
"Compiled" should be capitalized.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +*AAMultipleAlignment* classes allow users to represent groups
Use a backtick (`) rather than asterisks to mark these as functions.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +To create a *MultipleAlignment*, call the appropriate read
Use back ticks rather than asterisks.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +To see a more detailed version of your *MultipleAlignment*
Use back ticks rather than asterisks.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +keep, rather than to hide.  To do that, use the *invert*
Use back ticks.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +existing masks. The *append* argument allows you to specify
Use back ticks

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +*invert* argument to make things even more interesting.  In
Use back ticks

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +on *rowmask*, but it also works for *colmask*.  Before
Use back ticks

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +uses the "union" value for the *append* argument.
Use back ticks

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +this fraction of gaps *min.block.width*.
Use back ticks

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +matrix for usage eslewhere.  *as.matrix* is supported for
Use back ticks

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +using the *ape* package. For example if you needed to use the
Use BiocStyle to get the URL for CRAN package `ape`.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +One example of where you might want to use *as.matrix* is when
Use back ticks

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
Remove extra lines

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +```{r figure, fig=TRUE, eps=FALSE, fig.align = 'center', fig.cap='A tree produced by using strings with masked gaps'}
Should `fig.cap` not match removed line 259? Needs `echo=FALSE` to hide line 243, which should not be displayed in the final document.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +%could also have just done <<cluster2, fig=TRUE>>=
Remove this line; it shouldn't show up in the final document.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +```{r figure1, fig=TRUE, eps=FALSE, width=0.6,fig.align = 'center', height=5, fig.cap='A tree produced by using unmasked strings'}
Should `fig.cap` match the label in removed line 281? Needs `echo=FALSE` to hide line 260, which should not be displayed in the final document.

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +file, you can cast it to a *DNAStringSet* and then write
Use back ticks

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +title: "**MultipleAlignment Objects**"
Remove the double asterisks since the title will be automatically bolded by BiocStyle

2023-01-06 02:24 UTC, jwokaty commented on vignettes/MultipleAlignments.Rmd
> +```{r objectCreation}
Needs `message=FALSE`. Compare your knitted version with the original: you need to hide the messages.

2023-01-07 20:29 UTC, hpages commented
> Can we use .pngs for the figures rather than .pdfs since they don't format well?

of course, thanks

2023-01-10 10:09 UTC, BerylKanali commented
@jwokaty I made the requested changes.
Updated [HTML](https://rpubs.com/BerylK/982733) for comparison with [PDF](https://bioconductor.org/packages/release/bioc/vignettes/Biostrings/inst/doc/MultipleAlignments.pdf)

2023-06-27 18:02 UTC, hpages commented
@BerylKanali @jwokaty Where are we standing with this PR?

2023-06-27 18:32 UTC, jwokaty commented
I can check that the issues are resolved then notify @hpages.

2023-06-28 13:41 UTC, jwokaty commented
@hpages This is ready for your review.

2023-07-21 14:52 UTC, jwokaty approved these changes

2024-06-07 00:02 UTC, ahl27 commented
@hpages pinging to follow up on conversation from the other PR--is this also something that we need to merge?

2024-06-07 17:08 UTC, hpages commented
Just replaced `Biostrings2classes.Rnw` with Beryl's `Biostrings2classes.Rmd` (see commit a1fae35686d2fea09e896bd06a902c8ad1d5bbdf). Thanks for the reminder.

2024-06-07 17:08 UTC, closed without merging